
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "/opt/clion-2023.3.4/bin/cmake/linux/x64/share/cmake-3.27/Modules/CMakeDetermineSystem.cmake:211 (message)"
      - "CMakeLists.txt:2 (project)"
    message: |
      The system is: Linux - 5.15.0-101-generic - x86_64
  -
    kind: "message-v1"
    backtrace:
      - "/opt/clion-2023.3.4/bin/cmake/linux/x64/share/cmake-3.27/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "/opt/clion-2023.3.4/bin/cmake/linux/x64/share/cmake-3.27/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "/opt/clion-2023.3.4/bin/cmake/linux/x64/share/cmake-3.27/Modules/CMakeDetermineCCompiler.cmake:123 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:2 (project)"
    message: |
      Compiling the C compiler identification source file "CMakeCCompilerId.c" failed.
      Compiler: /usr/share/doc/gcc-12/gcc 
      Build flags: 
      Id flags:  
      
      The output was:
      Permission denied
      
      
  -
    kind: "message-v1"
    backtrace:
      - "/opt/clion-2023.3.4/bin/cmake/linux/x64/share/cmake-3.27/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "/opt/clion-2023.3.4/bin/cmake/linux/x64/share/cmake-3.27/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "/opt/clion-2023.3.4/bin/cmake/linux/x64/share/cmake-3.27/Modules/CMakeDetermineCCompiler.cmake:123 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:2 (project)"
    message: |
      Compiling the C compiler identification source file "CMakeCCompilerId.c" failed.
      Compiler: /usr/share/doc/gcc-12/gcc 
      Build flags: 
      Id flags: -c 
      
      The output was:
      Permission denied
      
      
  -
    kind: "message-v1"
    backtrace:
      - "/opt/clion-2023.3.4/bin/cmake/linux/x64/share/cmake-3.27/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "/opt/clion-2023.3.4/bin/cmake/linux/x64/share/cmake-3.27/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "/opt/clion-2023.3.4/bin/cmake/linux/x64/share/cmake-3.27/Modules/CMakeDetermineCCompiler.cmake:123 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:2 (project)"
    message: |
      Compiling the C compiler identification source file "CMakeCCompilerId.c" failed.
      Compiler: /usr/share/doc/gcc-12/gcc 
      Build flags: 
      Id flags: -Aa 
      
      The output was:
      Permission denied
      
      
  -
    kind: "message-v1"
    backtrace:
      - "/opt/clion-2023.3.4/bin/cmake/linux/x64/share/cmake-3.27/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "/opt/clion-2023.3.4/bin/cmake/linux/x64/share/cmake-3.27/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "/opt/clion-2023.3.4/bin/cmake/linux/x64/share/cmake-3.27/Modules/CMakeDetermineCCompiler.cmake:123 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:2 (project)"
    message: |
      Compiling the C compiler identification source file "CMakeCCompilerId.c" failed.
      Compiler: /usr/share/doc/gcc-12/gcc 
      Build flags: 
      Id flags: -D__CLASSIC_C__ 
      
      The output was:
      Permission denied
      
      
  -
    kind: "message-v1"
    backtrace:
      - "/opt/clion-2023.3.4/bin/cmake/linux/x64/share/cmake-3.27/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "/opt/clion-2023.3.4/bin/cmake/linux/x64/share/cmake-3.27/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "/opt/clion-2023.3.4/bin/cmake/linux/x64/share/cmake-3.27/Modules/CMakeDetermineCCompiler.cmake:123 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:2 (project)"
    message: |
      Compiling the C compiler identification source file "CMakeCCompilerId.c" failed.
      Compiler: /usr/share/doc/gcc-12/gcc 
      Build flags: 
      Id flags: --target=arm-arm-none-eabi;-mcpu=cortex-m3 
      
      The output was:
      Permission denied
      
      
  -
    kind: "message-v1"
    backtrace:
      - "/opt/clion-2023.3.4/bin/cmake/linux/x64/share/cmake-3.27/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "/opt/clion-2023.3.4/bin/cmake/linux/x64/share/cmake-3.27/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "/opt/clion-2023.3.4/bin/cmake/linux/x64/share/cmake-3.27/Modules/CMakeDetermineCCompiler.cmake:123 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:2 (project)"
    message: |
      Compiling the C compiler identification source file "CMakeCCompilerId.c" failed.
      Compiler: /usr/share/doc/gcc-12/gcc 
      Build flags: 
      Id flags: -c;-I__does_not_exist__ 
      
      The output was:
      Permission denied
      
      
  -
    kind: "message-v1"
    backtrace:
      - "/opt/clion-2023.3.4/bin/cmake/linux/x64/share/cmake-3.27/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "/opt/clion-2023.3.4/bin/cmake/linux/x64/share/cmake-3.27/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "/opt/clion-2023.3.4/bin/cmake/linux/x64/share/cmake-3.27/Modules/CMakeDetermineCCompiler.cmake:123 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:2 (project)"
    message: |
      Compiling the C compiler identification source file "CMakeCCompilerId.c" failed.
      Compiler: /usr/share/doc/gcc-12/gcc 
      Build flags: 
      Id flags:  
      
      The output was:
      Permission denied
      
      
  -
    kind: "message-v1"
    backtrace:
      - "/opt/clion-2023.3.4/bin/cmake/linux/x64/share/cmake-3.27/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "/opt/clion-2023.3.4/bin/cmake/linux/x64/share/cmake-3.27/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "/opt/clion-2023.3.4/bin/cmake/linux/x64/share/cmake-3.27/Modules/CMakeDetermineCCompiler.cmake:123 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:2 (project)"
    message: |
      Compiling the C compiler identification source file "CMakeCCompilerId.c" failed.
      Compiler: /usr/share/doc/gcc-12/gcc 
      Build flags: 
      Id flags: -c 
      
      The output was:
      Permission denied
      
      
  -
    kind: "message-v1"
    backtrace:
      - "/opt/clion-2023.3.4/bin/cmake/linux/x64/share/cmake-3.27/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "/opt/clion-2023.3.4/bin/cmake/linux/x64/share/cmake-3.27/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "/opt/clion-2023.3.4/bin/cmake/linux/x64/share/cmake-3.27/Modules/CMakeDetermineCCompiler.cmake:123 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:2 (project)"
    message: |
      Compiling the C compiler identification source file "CMakeCCompilerId.c" failed.
      Compiler: /usr/share/doc/gcc-12/gcc 
      Build flags: 
      Id flags: -Aa 
      
      The output was:
      Permission denied
      
      
  -
    kind: "message-v1"
    backtrace:
      - "/opt/clion-2023.3.4/bin/cmake/linux/x64/share/cmake-3.27/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "/opt/clion-2023.3.4/bin/cmake/linux/x64/share/cmake-3.27/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "/opt/clion-2023.3.4/bin/cmake/linux/x64/share/cmake-3.27/Modules/CMakeDetermineCCompiler.cmake:123 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:2 (project)"
    message: |
      Compiling the C compiler identification source file "CMakeCCompilerId.c" failed.
      Compiler: /usr/share/doc/gcc-12/gcc 
      Build flags: 
      Id flags: -D__CLASSIC_C__ 
      
      The output was:
      Permission denied
      
      
  -
    kind: "message-v1"
    backtrace:
      - "/opt/clion-2023.3.4/bin/cmake/linux/x64/share/cmake-3.27/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "/opt/clion-2023.3.4/bin/cmake/linux/x64/share/cmake-3.27/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "/opt/clion-2023.3.4/bin/cmake/linux/x64/share/cmake-3.27/Modules/CMakeDetermineCCompiler.cmake:123 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:2 (project)"
    message: |
      Compiling the C compiler identification source file "CMakeCCompilerId.c" failed.
      Compiler: /usr/share/doc/gcc-12/gcc 
      Build flags: 
      Id flags: --target=arm-arm-none-eabi;-mcpu=cortex-m3 
      
      The output was:
      Permission denied
      
      
  -
    kind: "message-v1"
    backtrace:
      - "/opt/clion-2023.3.4/bin/cmake/linux/x64/share/cmake-3.27/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "/opt/clion-2023.3.4/bin/cmake/linux/x64/share/cmake-3.27/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "/opt/clion-2023.3.4/bin/cmake/linux/x64/share/cmake-3.27/Modules/CMakeDetermineCCompiler.cmake:123 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:2 (project)"
    message: |
      Compiling the C compiler identification source file "CMakeCCompilerId.c" failed.
      Compiler: /usr/share/doc/gcc-12/gcc 
      Build flags: 
      Id flags: -c;-I__does_not_exist__ 
      
      The output was:
      Permission denied
      
      
  -
    kind: "message-v1"
    backtrace:
      - "/opt/clion-2023.3.4/bin/cmake/linux/x64/share/cmake-3.27/Modules/CMakeDetermineCompilerId.cmake:1117 (message)"
      - "/opt/clion-2023.3.4/bin/cmake/linux/x64/share/cmake-3.27/Modules/CMakeDetermineCompilerId.cmake:86 (CMAKE_DETERMINE_COMPILER_ID_VENDOR)"
      - "/opt/clion-2023.3.4/bin/cmake/linux/x64/share/cmake-3.27/Modules/CMakeDetermineCCompiler.cmake:123 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:2 (project)"
    message: |
      Checking whether the C compiler is IAR using "" did not match "IAR .+ Compiler":
  -
    kind: "message-v1"
    backtrace:
      - "/opt/clion-2023.3.4/bin/cmake/linux/x64/share/cmake-3.27/Modules/CMakeDetermineCompilerId.cmake:1117 (message)"
      - "/opt/clion-2023.3.4/bin/cmake/linux/x64/share/cmake-3.27/Modules/CMakeDetermineCompilerId.cmake:86 (CMAKE_DETERMINE_COMPILER_ID_VENDOR)"
      - "/opt/clion-2023.3.4/bin/cmake/linux/x64/share/cmake-3.27/Modules/CMakeDetermineCCompiler.cmake:123 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:2 (project)"
    message: |
      Checking whether the C compiler is IAR using "" did not match "IAR .+ Compiler":
  -
    kind: "try_compile-v1"
    backtrace:
      - "/opt/clion-2023.3.4/bin/cmake/linux/x64/share/cmake-3.27/Modules/CMakeDetermineCompilerABI.cmake:57 (try_compile)"
      - "/opt/clion-2023.3.4/bin/cmake/linux/x64/share/cmake-3.27/Modules/CMakeTestCCompiler.cmake:26 (CMAKE_DETERMINE_COMPILER_ABI)"
      - "CMakeLists.txt:2 (project)"
    checks:
      - "Detecting C compiler ABI info"
    directories:
      source: "/home/synxther/codes/code_c/cmake-build-debug-compiler/CMakeFiles/CMakeScratch/TryCompile-2DU5ch"
      binary: "/home/synxther/codes/code_c/cmake-build-debug-compiler/CMakeFiles/CMakeScratch/TryCompile-2DU5ch"
    cmakeVariables:
      CMAKE_C_FLAGS: ""
      CMAKE_C_FLAGS_DEBUG: ""
      CMAKE_EXE_LINKER_FLAGS: ""
    buildResult:
      variable: "CMAKE_C_ABI_COMPILED"
      cached: true
      stdout: |
        Change Dir: '/home/synxther/codes/code_c/cmake-build-debug-compiler/CMakeFiles/CMakeScratch/TryCompile-2DU5ch'
        
        Run Build Command(s): /opt/clion-2023.3.4/bin/ninja/linux/x64/ninja -v cmTC_73e02
        [1/2] /usr/share/doc/gcc-12/gcc    -o CMakeFiles/cmTC_73e02.dir/CMakeCCompilerABI.c.o -c /opt/clion-2023.3.4/bin/cmake/linux/x64/share/cmake-3.27/Modules/CMakeCCompilerABI.c
        FAILED: CMakeFiles/cmTC_73e02.dir/CMakeCCompilerABI.c.o 
        /usr/share/doc/gcc-12/gcc    -o CMakeFiles/cmTC_73e02.dir/CMakeCCompilerABI.c.o -c /opt/clion-2023.3.4/bin/cmake/linux/x64/share/cmake-3.27/Modules/CMakeCCompilerABI.c
        /bin/sh: 1: /usr/share/doc/gcc-12/gcc: Permission denied
        ninja: build stopped: subcommand failed.
        
      exitCode: 1
  -
    kind: "try_compile-v1"
    backtrace:
      - "/opt/clion-2023.3.4/bin/cmake/linux/x64/share/cmake-3.27/Modules/CMakeTestCCompiler.cmake:56 (try_compile)"
      - "CMakeLists.txt:2 (project)"
    checks:
      - "Check for working C compiler: /usr/share/doc/gcc-12/gcc"
    directories:
      source: "/home/synxther/codes/code_c/cmake-build-debug-compiler/CMakeFiles/CMakeScratch/TryCompile-SUpkkS"
      binary: "/home/synxther/codes/code_c/cmake-build-debug-compiler/CMakeFiles/CMakeScratch/TryCompile-SUpkkS"
    cmakeVariables:
      CMAKE_C_FLAGS: ""
      CMAKE_C_FLAGS_DEBUG: ""
      CMAKE_EXE_LINKER_FLAGS: ""
    buildResult:
      variable: "CMAKE_C_COMPILER_WORKS"
      cached: true
      stdout: |
        Change Dir: '/home/synxther/codes/code_c/cmake-build-debug-compiler/CMakeFiles/CMakeScratch/TryCompile-SUpkkS'
        
        Run Build Command(s): /opt/clion-2023.3.4/bin/ninja/linux/x64/ninja -v cmTC_4e831
        [1/2] /usr/share/doc/gcc-12/gcc    -o CMakeFiles/cmTC_4e831.dir/testCCompiler.c.o -c /home/synxther/codes/code_c/cmake-build-debug-compiler/CMakeFiles/CMakeScratch/TryCompile-SUpkkS/testCCompiler.c
        FAILED: CMakeFiles/cmTC_4e831.dir/testCCompiler.c.o 
        /usr/share/doc/gcc-12/gcc    -o CMakeFiles/cmTC_4e831.dir/testCCompiler.c.o -c /home/synxther/codes/code_c/cmake-build-debug-compiler/CMakeFiles/CMakeScratch/TryCompile-SUpkkS/testCCompiler.c
        /bin/sh: 1: /usr/share/doc/gcc-12/gcc: Permission denied
        ninja: build stopped: subcommand failed.
        
      exitCode: 1
...
